services:
  data-analysis:
    build:
      context: data-analysis
      target: development
    ports:
      - 38080:8080
    secrets:
      - db-password
  display:
    build:
      context: display
      target: development
    ports:
      - 30000:3000
      - 30080:80
  db:
    image: postgres:latest  # 使用Postgres数据库镜像
    volumes:
      - pg-data:/var/lib/postgresql/data  # 持久化存储
    environment:
      POSTGRES_USER: zhangjh
      POSTGRES_PASSWORD: pass.123
      POSTGRES_DB: analysis
    ports:
      - 35432:5432
volumes:
  pg-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  dev-network: 